name: Angular Static Website S3 Upload Template

on:
  workflow_call:
    inputs:
      s3_bucket_name:
        required: true
        type: string
      s3_region:
        required: true
        type: string          

jobs:
  deploy:
    name: Deploy Angular Front Into S3 Bucket
    runs-on: ubuntu-latest
    environment: 'Sandbox'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: frontend-artifact
          path: ./artifact

      - name: Decompress Artifact
        run: |
          ls -l ./artifact
          unzip ./artifact/dist.zip -d ./artifact
          rm -f dist.zip

      # TODO CONFIGURAR REPLACE TOKEN CUANDO PODAMOS USAR ENVIRONMENTS.    
      # - name: Replace Token
      #   uses: vinayaja/replace-token@v1.0.1
      #   with:
      #     gh-token: ${{ secrets.PAT_TOKEN }} 
      #     Environment-Name: 'dev'  
      #     Filespath: ${{ github.workspace}}/artifact/*/* 
      #     FileName: '.js'          

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ inputs.s3_region }}
        run: |
          aws s3 sync ${{ github.workspace}}/artifact/*/* s3://${{ inputs.s3_bucket_name }} --delete