name: Angular Build Template

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string           

jobs:
  build:
    name: Build Angular Front
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
     
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Run Unit Test
      #   run: npm run test           

      - name: Compress Directory
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: ./dist
          format: zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: ./dist.zip