name: ECS Deploy Task Definition Template

on:
  workflow_call: 
    inputs:
      environment:
        required: true
        type: string       
      aws_region:
        required: true
        type: string        
      image:
        required: true
        type: string
      task_def_arn:
        required: true
        type: string   
      container_name:
        required: true
        type: string
      service_name:
        required: true
        type: string   
      cluster_name:
        required: true
        type: string
      aws_account:
        required: true
        type: string   
      roletoassume:
        required: true
        type: string        
        
permissions:
  contents: read
  id-token: write        

jobs:
  build:
    name: Deploy ECS
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ inputs.aws_account }}:role/${{ inputs.roletoassume }}
          aws-region: us-east-1

      - name: Render Amazon ECS task definition
        env:
          AWS_REGION: ${{ inputs.aws_region }}        
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn:  ${{ inputs.task_def_arn }} 
          container-name: ${{ inputs.container_name }} 
          image: ${{ inputs.image }} 
          environment-variables: "LOG_LEVEL=info"
          secrets: |
            SECRET_KEY=arn:aws:secretsmanager:us-east-1:741448950818:secret:dev/api-wallet-TCKSLQ

      - name: Deploy to Amazon ECS service
        env:
          AWS_REGION: ${{ inputs.aws_region }}         
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: ${{ inputs.service_name }} 
          cluster: ${{ inputs.cluster_name }} 