name: ECS Deploy Task Definition Template

on:
  workflow_call:
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true     
    inputs:
      environment:
        required: true
        type: string       
      aws_region:
        required: true
        type: string        
      image:
        required: true
        type: string
      task_def_arn:
        required: true
        type: string   
      container_name:
        required: true
        type: string
      service_name:
        required: true
        type: string   
      cluster_name:
        required: true
        type: string                 

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Render Amazon ECS task definition
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_REGION: ${{ inputs.aws_region }}        
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition-arn:  ${{ inputs.task_def_arn }} 
          container-name: ${{ inputs.container_name }} 
          image: ${{ inputs.image }} 
          environment-variables: "LOG_LEVEL=info"

      - name: Deploy to Amazon ECS service
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_REGION: ${{ inputs.aws_region }}         
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: ${{ inputs.service_name }} 
          cluster: ${{ inputs.cluster_name }} 