name: NestJS Docker Build and Push Template

on:
  workflow_call:  
    inputs:
      branch:
        required: true
        type: string      
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerhub_username:
        required: true
        type: string 
      dockerhub_token:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_token }} 

      - name: Validate Image Tag
        run: |
          if [[ ! "${{ inputs.image_tag }}" =~ ^[0-99]+\.[0-99]+\.[0-99]+$ ]]; then
            echo "Invalid tag format: ${{ inputs.image_tag }}. Tags must be in the format X.X.X (e.g., 1.0.0)."
            exit 1
          fi
          echo "${{ inputs.image_tag }} is a valid Tag!"

      - name: Install Dependencies
        run: |
          docker build \
            --file Dockerfile \
            --target builder \
            -t ${{ inputs.image_name }}:builder .

      # SE COMENTAN PRUEBAS UNITARIAS - TODO: REVISAR CON DEV ESTÁN FALLANDO
      # - name: Run Unit Test
      #   run: |
      #     docker run --rm ${{ inputs.image_name }}:builder npm run test            

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --target production \
            -t juarezlucavs/${{ inputs.image_name }}:${{ inputs.image_tag }} .    

      - name: Push Docker image
        run: |
          docker push juarezlucavs/${{ inputs.image_name }}:${{ inputs.image_tag }}        