name: NestJS Docker Build and Push Template

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      dockerhub_username: #Provisorio, cuando vayamos a ECR no va a ser falta
        required: true
        type: string
      dockerhub_token: #Provisorio, cuando vayamos a ECR no va a ser falta
        required: true
        type: string
      image_name: #Provisorio, cuando vayamos a ECR no va a ser falta
        required: true
        type: string
      image_tag: #Provisorio, cuando vayamos a ECR no va a ser falta
        required: true
        type: string              

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub_username }}
          password: ${{ inputs.dockerhub_token }}

      - name: Validate Image Tag
        run: |
          if [[ ! "${{ inputs.image_tag }}" =~ ^[0-99]+\.[0-99]+\.[0-99]+$ ]]; then
            echo "Invalid tag format: ${{ inputs.image_tag }}. Tags must be in the format X.X.X (e.g., 1.0.0)."
            exit 1
          fi
          echo "${{ inputs.image_tag }} is a valid Tag!"      

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --target builder \
            -t ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:builder .
          docker build \
            --file Dockerfile \
            --target production \
            -t ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.image_version }} .

      - name: Push Docker image
        run: |
          docker push ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.image_version }}