name: Terraform CI template

on:
  workflow_call:
    secrets:
      aws_access_key_id:
        required: false
      aws_secret_access_key:
        required: false
    inputs:    
      environment:
        required: true
        type: string
      aws_access_key_id:
        type: string
        required: true
      aws_secret_access_key:
        type: string
        required: true  

env:
  tf_version: '1.9.7'
  tg_version: '0.67.0'
  working_dir: 'us-east-1/dev'

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
  
  plan:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      
      - name: 'set ssh credentials'
        uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all plan'